import React, { useState } from 'react';
import type { DefensiveAction } from '../types';

interface DefensiveActionsProps {
  actions: DefensiveAction[];
}

export const DefensiveActions: React.FC<DefensiveActionsProps> = ({ actions }) => {
  const [completedMap, setCompletedMap] = useState<Record<string, boolean>>({});
  const [copied, setCopied] = useState(false);

  const toggleAction = (id: string) => {
    setCompletedMap((prev) => ({ ...prev, [id]: !prev[id] }));
  };

  const copyChecklist = () => {
    const lines = actions.map(
      (a) => `[${completedMap[a.id] ? 'X' : ' '}] [${a.priority}] ${a.action}: ${a.detail}`
    );
    navigator.clipboard.writeText(
      `DEFENSIVE MITIGATION CHECKLIST:\n\n${lines.join('\n\n')}\n\nGenerated by Digital Scam Investigator`
    );
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="panel-card" style={{ marginBottom: '24px' }}>
      <div className="panel-header">
        <div className="panel-title">
          <span>🛡️</span>
          <span>3. DEFENSIVE ACTION PROTOCOL</span>
          <span className="panel-title-badge">STEP-BY-STEP REMEDIATION</span>
        </div>
        <button type="button" className="btn-secondary" onClick={copyChecklist} style={{ fontSize: '12px' }}>
          {copied ? '✓ Checklist Copied' : '📋 Copy Checklist'}
        </button>
      </div>

      <p style={{ fontSize: '13px', color: 'var(--text-secondary)', marginBottom: '16px' }}>
        Follow these prioritized countermeasures to safeguard your accounts, funds, and personal data:
      </p>

      <div className="actions-grid">
        {actions.map((act) => {
          const isDone = !!completedMap[act.id];

          return (
            <div
              key={act.id}
              className="action-item"
              style={{
                opacity: isDone ? 0.6 : 1,
                textDecoration: isDone ? 'line-through' : 'none',
              }}
            >
              <input
                type="checkbox"
                checked={isDone}
                onChange={() => toggleAction(act.id)}
                style={{ marginTop: '4px', cursor: 'pointer', width: '16px', height: '16px' }}
                title="Mark this action completed"
              />

              <div style={{ flex: 1 }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '4px' }}>
                  <span className={`action-priority-badge priority-${act.priority}`}>
                    {act.priority}
                  </span>
                  <strong style={{ fontSize: '14px', color: 'var(--text-primary)' }}>
                    {act.action}
                  </strong>
                  <span style={{ fontSize: '11px', color: 'var(--text-muted)' }}>
                    ({act.category})
                  </span>
                </div>
                <div style={{ fontSize: '13px', color: 'var(--text-secondary)', lineHeight: 1.5 }}>
                  {act.detail}
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};
